<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<link rel="stylesheet" href="res/bootstrap.min.css" type="text/css" />
		<link rel="stylesheet" href="res/bootstrap-theme.min.css" type="text/css" />
		<link rel="stylesheet" href="res/styles.css" type="text/css" />

		<!--         actually only for image data sets         -->
		<link rel="stylesheet" href="res/blueimp-gallery.min.css" type="text/css" />

		<script src="res/jquery.min.js"></script>
		<script src="res/bootstrap.min.js"></script>

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="//oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

		<script src="js/right-click-blocker.js"></script>
	</head>

	<body>
