		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
					</button>
				</div>

				<div class="collapse navbar-collapse" id="navbar-collapse">
					<ul class="nav navbar-nav">
						<li><a href="javascript:history.back();"><span class="glyphicon glyphicon-chevron-left"></span></a></li>
						<li><a href="<?php echo BASE_DIR; ?>"><span class="glyphicon glyphicon-home"></span></a></li>
					</ul>
					<form class="navbar-form navbar-right" role="search">
						<input type="hidden" name="action" value="search" />
						<input type="text" class="form-control" name="subject" autocomplete="off" placeholder="Datensatz finden" />
						<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
					</form>
					<ul class="nav navbar-nav navbar-right">
						<li><a href="?action=info&subject=FAQ" class="link-highlighted"><?php echo _( 'faq' ); ?></a></li>
					</ul>
				</div>
			</div>
		</nav>
		<div class="container" style="padding-top: 60px;">
			<div class="row">
				<div class="col-lg-12">
					<h1>Datentankstelle <small><?php echo _( 'by' ); ?> Wikimedia Deutschland e. V.</small></h1>
				</div>
			</div>
		</div>
