		<div id="push"></div>
	</div>
	<div id="footer">
		<div class="row">
			<div class="col-xs-2"></div>
			<div class="col-xs-8">
				<div style="text-align: center; line-height: 2em;">
					<?php echo _( 'service_by_wikimedia' ); ?><br />
					<a href="?action=info&subject=Lizenzhinweise" class="link-highlighted"><?php echo _( 'licence_information' ); ?></a> | 
					<a href="?action=info&subject=Impressum" class="link-highlighted"><?php echo _( 'imprint' ); ?></a>
				</div>
			</div>
			<div class="col-xs-2">
				<img src="img/wmde-logo.png" />
			</div>
		</div>
	</div>
</body>

</html>
