		<div id="push"></div>
	</div>
	<div id="footer">
		<div class="container" style="text-align: center;">
			<img src="img/wmde-logo.png" style="padding-right: 10px;" />
			Die Datentankstelle ist ein Service von Wikimedia Deutschland e. V.<br />
			<a href="?action=info&subject=Lizenzhinweise" class="link-highlighted">Lizenzhinweise</a>
			<a href="?action=info&subject=Impressum" class="link-highlighted">Impressum</a>
		</div>
	</div>
</body>

</html>
