		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="container-fluid">
				<div class="navbar-header">
					<ul class="navbar-nav nav">
						<li style="display: inline-block; margin-left: 20px;"><a class="active" href="javascript:history.back();"><span class="glyphicon glyphicon-chevron-left"></span> <?php echo _( 'back' ); ?></a></li>
						<li style="display: inline-block;"><a href="<?php echo BASE_DIR; ?>"><span class="glyphicon glyphicon-home"></span> <?php echo _( 'front_page' ); ?></a></li>
						<button type="button" class="navbar-toggle" style="margin-right: 30px;" data-toggle="collapse" data-target="#navbar-collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
					</ul>
				</div>

				<div class="collapse navbar-collapse" id="navbar-collapse">
					<div class="col-sm-6 col-md-6 pull-right">
						<ul class="nav navbar-nav">
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<?php echo _( 'language' ); ?> <span class="caret"></span>
								</a>
								<ul class="dropdown-menu">
									<?php foreach ( LanguageHandler::supportedLanguages() as $lang => $_): ?>
										<?php $queryString = http_build_query( array_merge( $_GET, array( 'lang' => $lang ) ) ); ?>
										<li><a href="?<?php echo $queryString ?>"><?php echo _( 'lang_' . $lang ); ?></a></li>
									<?php endforeach; ?>
								</ul>
							</li>
							<li><a href="?action=info&subject=Hilfe" class="link-highlighted"><?php echo _( 'help' ); ?></a></li>
						</ul>
						<form class="navbar-inline" srole="search">
							<div class="input-group" style="padding: 8px 0 10px 0;">
								<input type="text" class="form-control" placeholder="Datensatz finden" name="subject" />
								<input type="hidden" name="action" value="search" />
					            <div class="input-group-btn">
									<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</nav>
		<div class="container" style="padding-top: 60px;">
			<div class="row">
				<div class="col-lg-12">
					<h1>Datentankstelle <small><?php echo _( 'by' ); ?> Wikimedia Deutschland e. V.</small></h1>
				</div>
			</div>
		</div>
