		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="container-fluid">
				<div class="navbar-header">
					<ul class="navbar-nav nav">
						<li style="display: inline-block; margin-left: 20px;"><a class="active" href="javascript:history.back();"><span class="glyphicon glyphicon-chevron-left"></span> Zurück</a></li>
						<li style="display: inline-block;"><a href="<?php echo BASE_DIR; ?>"><span class="glyphicon glyphicon-home"></span> Startseite</a></li>
						<button type="button" class="navbar-toggle" style="margin-right: 30px;" data-toggle="collapse" data-target="#navbar-collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
					</ul>
				</div>

				<div class="collapse navbar-collapse" id="navbar-collapse">
					<div class="col-sm-6 col-md-6 pull-right">
						<ul class="nav navbar-nav">
							<li><a href="?action=info&subject=FAQ" class="link-highlighted">FAQ</a></li>
						</ul>
						<form class="navbar-inline" srole="search">
							<div class="input-group" style="padding-bottom: 10px;">
								<input type="text" class="form-control" placeholder="Datensatz finden" name="subject" />
								<input type="hidden" name="action" value="search" />
					            <div class="input-group-btn">
									<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</nav>
		<div class="container" style="padding-top: 60px;">
			<div class="row">
				<div class="col-lg-12">
					<h1>Datentankstelle<small> von&nbsp;Wikimedia&nbsp;Deutschland&nbsp;e.&nbsp;V.</small></h1>
				</div>
			</div>
		</div>
