	<div class="col-md-12">
		<div id="blueimp-gallery-carousel<?php echo $count; ?>" class="blueimp-gallery blueimp-gallery-carousel blueimp-gallery-controls">
			<div class="slides"></div>
			<ol class="indicator"></ol>
			<p class="description"></p>
		</div>
	</div>
	<div id="links<?php echo $count; ?>">
<?php foreach ( $fileList as $file ): ?>
		<a href="/datentankstelle/<?php echo $file; ?>" data-description="<?php echo Util::getImageDescription( $file ); ?>"></a>
<?php endforeach; ?>
	</div>
