	<div class="col-md-12">
		<div id="blueimp-gallery-carousel<?php echo $count; ?>" class="blueimp-gallery blueimp-gallery-carousel">
			<div class="slides"></div>
			<h3 class="title"></h3>
			<a class="prev">‹</a>
			<a class="next">›</a>
			<a class="play-pause"></a>
			<ol class="indicator"></ol>
		</div>
	</div>
	<script>
		var imageList<?php echo $count; ?> = <?php echo json_encode( $fileList ); ?>;
	</script>
