<script>
<?php if ( Util::isLocalSystem() ): ?>
	$( document ).ready( function() {
		window.setInterval( checkDevices, 2000 );
	});
<?php endif; ?>
	var connectedDevice = '';
	var initialCopyStatus = 'Betankung läuft...';
	var initialCopyStatusClasses = 'glyphicon glyphicon-download text-primary';
	var checkDevices = function() {
		$.ajax({
			url: "index.php",
			data: { action: "check" }
		}).done( function( response ) {
			// TODO: consider more than one connected device
			var objDevices = $.parseJSON( response );
			connectedDevice = '';
			$.each( objDevices, function( index, value ) {
				connectedDevice = value;
			});

			// disable download button if no storage device connected
			if ( connectedDevice === '' ) {
				$( ".btnDownload" ).attr( "disabled", "disabled" );
				$( ".dlEnabled" ).hide();
				$( ".dlDisabled" ).show();
			} else {
				$( ".btnDownload" ).attr( "disabled", false );
				$( ".dlEnabled" ).show();
				$( ".dlDisabled" ).hide();
			}
		});
	}

	var copyDataSet = function( title ) {
		$( '.digit' ).removeClass( 'animationStop' );
		$.ajax({
			url: "index.php",
			data: {
				action: "download",
				subject: title,
				dev: connectedDevice
			},
			beforeSend: function() {
				$( '#copyStatus' ).text( initialCopyStatus );
				$( '#copyStatus-icon' ).attr( "class", initialCopyStatusClasses );
				$( '#copyDialog' ).modal();
			}
		}).done( function( response ) {
			$( '.digit' ).addClass( 'animationStop' );
			var response = $.parseJSON( response );
			if ( response.status === 'success' ) {
				$( '#copyStatus' ).html( response.message + "<br /><span style='color: #428BCA; cursor: pointer;' onclick='unmountDevice( \"" + connectedDevice + "\" )'>Speichergerät trennen</span>" );
				$( '#copyStatus-icon' ).attr( "class", "glyphicon glyphicon-ok text-success" );
			} else {
				$( '#copyStatus' ).text( response.message );
				$( '#copyStatus-icon' ).attr( "class", "glyphicon glyphicon-remove text-warning" );
			}
		});
	}

	var unmountDevice = function( deviceLabel ) {
		$.ajax({
			url: "index.php",
			data: {
				action: "unmount",
				subject: deviceLabel
			}
		}).done( function( response ) {
			var response = $.parseJSON( response );
			if ( response.status === 'success' ) {
				$( '#copyStatus' ).text( response.message );
				$( '#copyStatus-icon' ).attr( "class", "glyphicon glyphicon-ok text-success" );
			} else {
				$( '#copyStatus' ).text( response.message );
				$( '#copyStatus-icon' ).attr( "class", "glyphicon glyphicon-remove text-warning" );
			}
		});
	}

	var openCopyDialog = function() {
		$( "#dialog-message" ).dialog({
			modal: true,
			buttons: {
				Ok: function() {
					$( this ).dialog( "close" );
				}
			}
		});
	}
</script>
<?php if ( count( $this->_dataSets ) > 0 ): ?>
	<?php $count = 0; ?>
	<?php foreach ( $this->_dataSets as $item ): ?>
				<div class="row">
					<div class="col-xs-12">
						<div class="tile setTile">
						<?php $fileList = $this->getFileListByTitle( $item["Title"] ); ?>
						<?php if ( !empty( $item["Icon"] ) ): ?>
							<img src="<?php echo $this->createImageThumb( $item["Icon"], 32 ); ?>" style="float: left; margin: 16px 10px 0 0;" />
						<?php endif; ?>
							<div onclick="$('#dataSetDetail<?php echo $count; ?>').slideToggle(); <?php if ( $item["MediaType"] === "images" && $fileList ) { ?>startSlideshow( '<?php echo $count; ?>' );<?php }?>">
								<h3><?php echo CategoryInfo::removeLanguageEndingFromTitle( $item["Title"] ); ?></h3>
								<p class="lead"><?php echo nl2br( $item["ShortDescription"] ); ?></p>
							</div>
							<div class="row" style="display: none;" id="dataSetDetail<?php echo $count; ?>">
								<div class="col-sm-7 col-xs-12">
									<p>
										<?php if ( !empty( $item["Image"] ) ): ?>
										<img src="<?php echo $this->createImageThumb( $item["Image"] ); ?>" class="img-rounded" style="float: left; margin-right: 10px;" />
										<?php endif; ?>
										<?php echo nl2br( $item["LongDescription"] ); ?>
									</p>
								</div>
								<div class="col-sm-5 col-xs-12">
									<div class="infoBox tile">
										<p class="lead">Dateidetails</p>
										<dt>Autor</dt>
										<dd><?php echo nl2br( $item["Author"] ); ?></dd>
										<?php if ( !empty( $item["Supplier"] ) ): ?>
										<dt>Bereitgestellt durch</dt>
										<dd><?php echo nl2br( $item["Supplier"] ); ?></dd>
										<?php endif; ?>
										<dt>Lizenz</dt>
										<dd><?php echo nl2br( $this->getLicenceLink( $item["Licence"] ) ); ?></dd>
										<dt>Dateigr&ouml;&szlig;e</dt>
										<dd><?php echo Util::calcFileSize( $item["FileName"] ); ?></dd>
										<dt>Dateityp</dt>
										<dd><?php echo Util::getFileType( $item["FileName"] ); ?></dd>

										<?php if ( Util::isLocalSystem() ): ?>
										<div class="dlDisabled" style="padding: 8px; background-color: #F5F5F5;">
											<p style="text-align: center;">
												Speichermedium auf der rechten Seite der Zapfs&auml;ule anschlie&szlig;en zum Auftanken mit diesem Datenset<br />
											</p>
										</div>

										<div class="dlEnabled" style="display: none; text-align: center;">
											<button type="button" class="btn btn-lg btnDownload" onclick="copyDataSet( '<?php echo $item["FileName"]?>' )" class="btnDownload" disabled="disabled" class="btn btn-lg">Auftanken</button>
										</div>
										<?php else: ?>
										<div style="text-align: center;">
											<form name="dlForm" method="GET" action="<?php echo DOWNLOAD_FOLDER . $item["FileName"]; ?>">
												<button type="submit" id="btnDownload" class="btn btn-lg">Auftanken</button>
											</form>
										</div>
										<?php endif; ?>
									</div>
								</div>
								<div class="row">
									<div class="col-xs-12">
										<p>
											<?php $this->includeMediaPreview( $count, $item["MediaType"], $fileList ); ?>
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
		<?php $count++; ?>
	<?php endforeach; ?>
<?php endif; ?>

			<script src="res/blueimp-gallery.min.js"></script>
			<script>
				var startSlideshow = function( count ) {
					var gallery = blueimp.Gallery(
						document.getElementById( 'links' + count ).getElementsByTagName( 'a' ),
						{
							container: '#blueimp-gallery-carousel' + count,
							carousel: true,
							onslide: function ( index, slide ) {
								var text = this.list[index].getAttribute( 'data-description' ),
									node = this.container.find( '.description' );
								node.empty();
								if (text) {
									node[0].appendChild( document.createTextNode( text ) );
								}
							}
						}
					);
				}
			</script>
			</div>
		</div>
	</div>

	<div class="modal fade" id="copyDialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title"><?php echo _( 'fill_up' ); ?>...</h4>
				</div>
				<div class="modal-body">
					<span id="copyStatus-icon" class="glyphicon glyphicon-download text-primary" style="float: left; font-size: 3em; margin-right: 20px;"></span>
					<p id="copyStatus" style="line-height: 3em;">
						<?php echo _( 'fill_up_in_progress' ); ?>...<br />
					</p>

					<div id="digitRoll">
						<div id="wrapper1" class="digit"></div>
						<div id="wrapper2" class="digit"></div>
						<div id="wrapper3" class="digit"></div>
						<div id="wrapper4" class="digit" style="border: none;"></div>
						<div style="clear: both;"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<img src="img/counter-sprite.png" style="display: none;"/>