<?php include( "templates/" . $_SESSION["skin"] . "/controls.tpl.phtml" ); ?>
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-1">
			<a href="?action=category&subject=Hauptkategorie">
				<div class="tile catTile" style="text-align: center; line-height: 7em; font-size: 2em;">Auftanken</div>
			</a>
		</div>
		<div class="col-md-4 col-md-offset-1">
			<div class="tile catTile" style="text-align: center; line-height: 7em; font-size: 2em;">Informieren</div>
		</div>
	</div>
</div>
