<?php include( "templates/" . $_SESSION["skin"] . "/controls.tpl.phtml" ); ?>
<div class="container">
	<div class="row hidden-xs" style="height: 80px;">
		
	</div>
	<div class="row">
		<div class="col-md-4 col-md-offset-1">
			<a href="?action=category&subject=Auftanken" class="catLink">
				<div class="tile catTile" style="text-align: center; line-height: 7.5em; font-size: 2em;">Auftanken</div>
			</a>
		</div>
		<div class="col-md-4 col-md-offset-1">
			<a href="?action=info&subject=FAQ" class="catLink">
				<div class="tile catTile" style="padding-top: 80px; text-align: center; font-size: 2em;">
					Was ist die Datentankstelle?
				</div>
			</a>
		</div>
	</div>
</div>
