<?php include( "templates/" . $_SESSION["skin"] . "/controls.tpl.phtml" ); ?>
<div class="container">
	<div class="row hidden-xs" style="height: 80px;">
		
	</div>
	<div class="row">
		<div class="col-md-4 col-md-offset-1">
			<a href="?action=info&subject=FAQ" class="catLink">
				<div class="tile catTile" style="position: relative;">
					<div class="tileBackgroundImage" style="background-image: url(<?php echo $mainCat->getIconFileUrl( "Datei:Icon_22.png", 128 ); ?>);"></div>
					<div style="padding: 0; margin: 0; width: 100%; height: 254px; position: absolute; top: 33%; left: 0;">
						<h3 style="text-align: center;"><?php echo _( 'what_is_datentankstelle' ); ?></h3>
					</div>
				</div>
			</a>
		</div>
		<div class="col-md-4 col-md-offset-2">
			<a href="<?php echo CategoryInfo::categoryURL( $mainCat->getCatInfo()['Id'] ); ?>" class="catLink">
				<?php $catInfo = $mainCat->getCatInfo(); ?>
				<div class="tile catTile">
					<?php if ( !empty( $catInfo["Icon"] ) ): ?>
					<div class="tileBackgroundImage" style="background-image: url(<?php echo $mainCat->getIconFileUrl( $catInfo["Icon"], 128 ); ?>);">
					</div>
					<?php endif; ?>

					<h3 style="text-align: center; line-height: 7.5em;"><?php echo CategoryInfo::removeLanguageEndingFromTitle( $mainCat->getCatTitle() ); ?></h3>
				</div>
			</a>
		</div>
	</div>
</div>
