			<div class="row">
				<div class="col-md-4">
					<button type="button" class="btn btn-default" onclick="javascript:history.back();">Zurück</button>
				</div>
				<div class="col-md-8" style="text-align: right;">
					<form method="GET">
						Suchen:
						<input type="text" name="subject" />
						<input type="hidden" name="action" value="search" />
						<button>Go</button>
					</form>
				</div>
			</div>
