		<nav class="navbar navbar-default" role="navigation">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
					</button>
				</div>

				<div class="collapse navbar-collapse" id="navbar-collapse">
					<ul class="nav navbar-nav">
						<li><a href="javascript:history.back();"><span class="glyphicon glyphicon-chevron-left"></span></a></li>
						<li><a href="<?php echo BASE_DIR; ?>"><span class="glyphicon glyphicon-home"></span></a></li>
					</ul>
					<form class="navbar-form navbar-right" role="search">
						<input type="hidden" name="action" value="search" />
						<input type="text" class="form-control" name="subject" autocomplete="off" placeholder="Datensatz finden" />
						<button type="submit" class="btn btn-default"><img src="img/search.png" /></button>
					</form>
				</div>
			</div>
		</nav>
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<h1>Datentankstelle<small> von Wikimedia Deutschland e. V.</small></h1>
					<div class="row">
						<div class="col-lg-12">
<?php if ( isset( $this->_breadCrumbs ) && count( $this->_breadCrumbs ) > 0 ): ?>
							<ol class="breadcrumb">
	<?php foreach ( array_reverse( $this->_breadCrumbs ) as $index => $crumb ): ?>
		<?php if ( count( $this->_breadCrumbs ) - 1 === $index ): ?>
								<li class="active"><?php echo $crumb; ?></li>
		<?php else: ?>
								<li><a href="?action=category&subject=<?php echo $crumb; ?>"><?php echo $crumb; ?></a></li>
		<?php endif; ?>
	<?php endforeach; ?>
							</ol>
<?php endif; ?>
						</div>
					</div>
				</div>
			</div>
		</div>
