	<div class="row">
		<div class="col-md-12">
			<h1>Datentankstelle</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-md-4 col-md-offset-1">
			<a href="?action=category&subject=Hauptkategorie">
				<div class="tile catTile" style="text-align: center; line-height: 7em; font-size: 2em;">Stöbern</div>
			</a>
		</div>
		<div class="col-md-4 col-md-offset-2">
			<div class="tile catTile" style="text-align: center; line-height: 7em; font-size: 2em;">Informieren</div>
		</div>
	</div>
